# Generated by Django 2.0.3 on 2020-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='status',
            field=models.CharField(default='initiated', max_length=64),
        ),
    ]
